name: 'Deploy to Vercel Staging'
description: 'Deploys the application to Vercel staging environment'

outputs:
  deployment-url:
    description: 'The URL of the Vercel deployment'
    value: ${{ steps.deploy.outputs.deployment-url }}

inputs:
  vercel-token:
    description: 'Vercel authentication token'
    required: true
  vercel-org-id:
    description: 'Vercel organization ID'
    required: true
  vercel-project-id:
    description: 'Vercel project ID'
    required: true
  sha:
    description: 'Commit SHA'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Vercel CLI
      shell: bash
      run: npm install --global vercel@latest

    - name: Configure Vercel environment
      shell: bash
      env:
        VERCEL_ORG_ID: ${{ inputs.vercel-org-id }}
        VERCEL_PROJECT_ID: ${{ inputs.vercel-project-id }}
      run: vercel pull --yes --environment=preview --token=${{ inputs.vercel-token }}

    - name: Build application
      shell: bash
      env:
        VERCEL_ORG_ID: ${{ inputs.vercel-org-id }}
        VERCEL_PROJECT_ID: ${{ inputs.vercel-project-id }}
      run: vercel build --token=${{ inputs.vercel-token }}

    - name: Deploy to Vercel
      shell: bash
      env:
        VERCEL_ORG_ID: ${{ inputs.vercel-org-id }}
        VERCEL_PROJECT_ID: ${{ inputs.vercel-project-id }}
      id: deploy
      run: |
        echo "deployment-url=$(vercel deploy --prebuilt --token=${{ inputs.vercel-token }})" >> $GITHUB_OUTPUT
