name: 'Deploy to Vercel Production'
description: 'Deploys the application to Vercel production environment'

inputs:
  vercel-token:
    description: 'Vercel authentication token'
    required: true
  vercel-org-id:
    description: 'Vercel organization ID'
    required: true
  vercel-project-id:
    description: 'Vercel project ID'
    required: true
  sha:
    description: 'Commit SHA'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Vercel CLI
      shell: bash
      run: npm install --global vercel@latest

    - name: Configure Vercel environment
      shell: bash
      env:
        VERCEL_ORG_ID: ${{ inputs.vercel-org-id }}
        VERCEL_PROJECT_ID: ${{ inputs.vercel-project-id }}
      run: vercel pull --yes --environment=production --token=${{ inputs.vercel-token }}

    - name: Build application
      shell: bash
      env:
        VERCEL_ORG_ID: ${{ inputs.vercel-org-id }}
        VERCEL_PROJECT_ID: ${{ inputs.vercel-project-id }}
      run: vercel build --prod --token=${{ inputs.vercel-token }}

    - name: Deploy to Vercel
      shell: bash
      env:
        VERCEL_ORG_ID: ${{ inputs.vercel-org-id }}
        VERCEL_PROJECT_ID: ${{ inputs.vercel-project-id }}
      run: |
        DEPLOYMENT_URL=$(vercel deploy --prebuilt --prod --token=${{ inputs.vercel-token }})
        echo "DEPLOYMENT_URL=$DEPLOYMENT_URL" >> $GITHUB_ENV
          
    - name: Update GitHub deployment status
      uses: actions/github-script@v6
      with:
        script: |
          const deployment = await github.rest.repos.createDeployment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: '${{ inputs.sha }}',
            environment: 'Production',
            auto_merge: false,
            required_contexts: [],
            description: 'Production deployment via Vercel'
          });
          
          await github.rest.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            deployment_id: deployment.data.id,
            state: 'success',
            environment_url: process.env.DEPLOYMENT_URL,
            description: '✨ Production deployment completed'
          });
