name: Deploy Production
on:
  release:
    types: [published]

# Ensure only one production deployment can run at a time
concurrency:
  group: production
  cancel-in-progress: false

env:
  NODE_ENV: production
  HUSKY: 0
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  quality:
    name: Quality Checks
    runs-on: ubuntu-latest
    if: github.event.release.target_commitish == 'main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup environment
        uses: ./.github/actions/setup-environment
      
      - name: Run quality assurance checks
        uses: ./.github/actions/quality-checks

  production:
    name: Deploy Production
    needs: quality
    runs-on: ubuntu-latest
    if: github.event.release.target_commitish == 'main'
    permissions:
      deployments: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup environment
        uses: ./.github/actions/setup-environment
        
      - name: Deploy to Vercel
        uses: ./.github/actions/deploy/vercel/production
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          sha: ${{ github.sha }}
