name: Deploy Staging
on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

# Ensure only one staging deployment can run at a time
concurrency:
  group: staging
  cancel-in-progress: false

env:
  HUSKY: 0
  NODE_ENV: staging
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  quality:
    name: Quality Checks
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup environment
        uses: ./.github/actions/setup-environment
      
      - name: Run quality assurance checks
        uses: ./.github/actions/quality-checks

  staging:
    name: Deploy Staging
    needs: quality
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      deployments: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup environment
        uses: ./.github/actions/setup-environment
        
      - name: Deploy to Vercel
        uses: ./.github/actions/deploy/vercel/staging
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          sha: ${{ github.sha }}
