name: Deploy Production
on:
  push:
    branches:
      - main

# Ensure only one production deployment can run at a time
concurrency:
  group: production
  cancel-in-progress: false

jobs:
  deploy:
    name: Test and Deploy Production
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup environment
        uses: ./.github/actions/setup-environment
      
      - name: Run quality assurance checks
        uses: ./.github/actions/quality-checks
        
      - name: Deploy to production
        uses: ./.github/actions/vercel-deploy-production
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          sha: ${{ github.sha }}
