name: Deploy Preview

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write
  deployments: write

# Prevent concurrent deployments for same PR
concurrency:
  group: "pages-${{ github.event.pull_request.number }}"
  cancel-in-progress: true

jobs:
  deploy-preview:
    if: |
      github.event.pull_request.draft == false &&
      (github.event.pull_request.head.repo.fork == false ||
       (github.event.pull_request.head.repo.fork == true &&
        github.event.pull_request.author_association == 'CONTRIBUTOR'))
    runs-on: ubuntu-latest
    environment:
      name: preview-${{ github.event.pull_request.number }}
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          # Fetch depth 1 for efficiency
          fetch-depth: 1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      # Security check for secrets
      - name: Check PR author
        id: check_author
        run: |
          if [[ "${{ github.event.pull_request.head.repo.fork }}" == "true" ]]; then
            echo "::warning::PR is from a fork. Limited environment variables will be available."
          fi

      - name: Build
        run: npm run build:staging
        env:
          NODE_ENV: production
          VITE_APP_ENV: staging
          # Only expose non-sensitive environment variables to fork PRs
          VITE_APP_BASE_URL: ${{ github.event.pull_request.head.repo.fork == false && secrets.STAGING_BASE_URL || '' }}
          VITE_APP_API_URL: ${{ github.event.pull_request.head.repo.fork == false && secrets.STAGING_API_URL || '' }}
          VITE_APP_GOOGLE_ANALYTICS_ID: ${{ github.event.pull_request.head.repo.fork == false && secrets.STAGING_GA_ID || '' }}
          VITE_BASE_PATH: '/myself-react-app/preview/pr-${{ github.event.pull_request.number }}'
          VITE_APP_ENABLE_DEBUG: ${{ github.event.pull_request.head.repo.fork == false }}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@main
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            const previewUrl = '${{ steps.deployment.outputs.page_url }}';
            const message = `🚀 Preview deployment is ready!\n\n[View Preview](${previewUrl})`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });

      - name: Output Preview URL
        run: |
          echo "::notice title=Preview URL::${{ steps.deployment.outputs.page_url }}"
